### ISSUE TITLE
How to up vote

### ISSUE THREAD

**Issue by ghost** [copying/DubBot#2]
this api is very good but i need to know one thing if its possible how would one make the bot upvote a song?

**Comment by mangelats** [comment]
Sorry for having the wiki under construction, it is updated in the free time I have.

To updub a song simply use `song.updub()`. You can get the song by using `room.currentSong` or when the room's `'song-change'` event is emitted.

To downdub simply use `song.downdub()`

**Comment by ghost** [comment]
Thanks
